#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-email-system123"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
ENVIRONMENT = "production"
MAX_ATTACHMENT_SIZE = "10485760"  # 10MB
DEFAULT_PAGE_SIZE = "20"

# D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "email-db"
database_id = "ccf71e0c-dc6a-42b6-92e1-a99534a050a8"
migrations_dir = "migrations"

# R2 存储桶（附件）
[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "email-attachments"

# KV 命名空间（会话和缓存）
[[kv_namespaces]]
binding = "KV"
id = "551ad49414d641c9bacfef8c6482bf32"
preview_id = "your-preview-kv-id"

# 队列（需要付费计划，免费版本不使用）
# [[queues.producers]]
# binding = "EMAIL_QUEUE"
# queue = "email-processing"

# [[queues.consumers]]
# queue = "email-processing"
# max_batch_size = 10
# max_batch_timeout = 30

# Email Workers 配置
[email]
name = "cloudflare-email-system"

# 开发环境配置
[env.development]
vars = { ENVIRONMENT = "development" }

# Durable Objects（可选）
# [[durable_objects.bindings]]
# name = "USER_SESSION"
# class_name = "UserSession"
