# Cloudflare 一键部署配置

[build]
command = "npm ci"
cwd = "."

[build.environment]
NODE_VERSION = "18"

# Worker 配置
[worker]
name = "cloudflare-email-system"
main = "src/index.ts"
compatibility_date = "2024-09-25"

# Pages 配置  
[pages]
build_command = ""
build_output_directory = "public"
root_directory = "."

# 必需的资源
[resources]
d1_databases = [
  { binding = "DB", database_name = "email-db" }
]

r2_buckets = [
  { binding = "ATTACHMENTS", bucket_name = "email-attachments" }
]

kv_namespaces = [
  { binding = "KV" }
]

queues = [
  { binding = "EMAIL_QUEUE", queue_name = "email-processing" }
]

# 环境变量
[env]
ENVIRONMENT = "production"
MAX_ATTACHMENT_SIZE = "10485760"
DEFAULT_PAGE_SIZE = "20"

# 必需的 Secrets（用户需要手动配置）
[secrets]
MAILCHANNELS_API_KEY = "required"
# 或者选择其他邮件服务：
# RESEND_API_KEY = "optional"
# SENDGRID_API_KEY = "optional"
